import type { ListingWithProfile } from "./supabase/types";

export const mockListings: ListingWithProfile[] = [
  {
    id: "1",
    user_id: "u1",
    title: "Bosch Professional Drill 18V",
    description: "High-quality cordless drill with 2 batteries. Perfect for home renovation or DIY projects. Includes various drill bits.",
    category: "power",
    price_per_day: 8,
    deposit: 30,
    city: "Vilnius",
    address: "Antakalnis district",
    images: ["https://images.unsplash.com/photo-1504148455328-c376907d081c?w=600&q=80"],
    is_available: true,
    created_at: "2025-03-01T10:00:00Z",
    profiles: { id: "u1", full_name: "Tomas Kazlauskas", avatar_url: null, phone: null, city: "Vilnius", created_at: "2024-11-01T00:00:00Z" },
  },
  {
    id: "2",
    user_id: "u2",
    title: "Kärcher K5 Pressure Washer",
    description: "Powerful 145 bar pressure washer. Great for cleaning cars, terraces, fences and more. 10m hose included.",
    category: "cleaning",
    price_per_day: 15,
    deposit: 50,
    city: "Kaunas",
    address: "Žaliakalnis",
    images: ["https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&q=80"],
    is_available: true,
    created_at: "2025-03-05T12:00:00Z",
    profiles: { id: "u2", full_name: "Rūta Petraitienė", avatar_url: null, phone: null, city: "Kaunas", created_at: "2024-12-01T00:00:00Z" },
  },
  {
    id: "3",
    user_id: "u3",
    title: "6m Telescopic Ladder",
    description: "Aluminium telescopic ladder, extends to 6 metres. Very stable and lightweight. Ideal for painting, roof work and gutter cleaning.",
    category: "construction",
    price_per_day: 10,
    deposit: 40,
    city: "Vilnius",
    address: "Šeškinė district",
    images: ["https://images.unsplash.com/photo-1581578731548-c64695cc6952?w=600&q=80"],
    is_available: true,
    created_at: "2025-03-10T09:00:00Z",
    profiles: { id: "u3", full_name: "Andrius Jankauskas", avatar_url: null, phone: null, city: "Vilnius", created_at: "2025-01-15T00:00:00Z" },
  },
  {
    id: "4",
    user_id: "u4",
    title: "Lawnmower Honda HRX537",
    description: "Self-propelled petrol lawnmower with 53cm cutting width. Mulching function included. Great condition.",
    category: "garden",
    price_per_day: 20,
    deposit: 60,
    city: "Klaipėda",
    address: "Debrecenas",
    images: ["https://images.unsplash.com/photo-1589923188651-268a9765e432?w=600&q=80"],
    is_available: true,
    created_at: "2025-03-12T14:00:00Z",
    profiles: { id: "u4", full_name: "Jurgita Mockienė", avatar_url: null, phone: null, city: "Klaipėda", created_at: "2025-02-01T00:00:00Z" },
  },
  {
    id: "5",
    user_id: "u1",
    title: "Makita Orbital Sander",
    description: "Random orbital sander 125mm. Includes dust bag and assorted sandpaper sheets. Perfect for furniture refinishing.",
    category: "power",
    price_per_day: 6,
    deposit: 20,
    city: "Vilnius",
    address: "Antakalnis district",
    images: ["https://images.unsplash.com/photo-1572981779307-38b8cabb2407?w=600&q=80"],
    is_available: false,
    created_at: "2025-03-15T11:00:00Z",
    profiles: { id: "u1", full_name: "Tomas Kazlauskas", avatar_url: null, phone: null, city: "Vilnius", created_at: "2024-11-01T00:00:00Z" },
  },
  {
    id: "6",
    user_id: "u5",
    title: "Concrete Mixer 140L",
    description: "Electric concrete mixer, 140 litre drum. Ideal for small construction projects, garden paths, posts.",
    category: "construction",
    price_per_day: 25,
    deposit: 80,
    city: "Šiauliai",
    address: "City centre",
    images: ["https://images.unsplash.com/photo-1590059390047-2e03e6660f5a?w=600&q=80"],
    is_available: true,
    created_at: "2025-03-18T08:00:00Z",
    profiles: { id: "u5", full_name: "Darius Butkus", avatar_url: null, phone: null, city: "Šiauliai", created_at: "2025-01-20T00:00:00Z" },
  },
];

export const mockCities = ["Vilnius", "Kaunas", "Klaipėda", "Šiauliai", "Panevėžys"];
